SET FOREIGN_KEY_CHECKS=0;
DROP TABLE caracteristicas;
DROP TABLE clientes;
DROP TABLE consultas;
DROP TABLE cotizacion_producto;
DROP TABLE cotizacion_servicio;
DROP TABLE cotizaciones;
DROP TABLE designaciones;
DROP TABLE observaciones;
DROP TABLE pagos;
DROP TABLE personal;
DROP TABLE plan_caracteristica;
DROP TABLE planes;
DROP TABLE presentaciones;
DROP TABLE producto_caracteristicas;
DROP TABLE productos;
DROP TABLE proyectos;
DROP TABLE revisiones;
DROP TABLE sanciones;
DROP TABLE servicio_caracteristicas;
DROP TABLE servicios;
DROP TABLE tareas;
DROP TABLE usuarios;
DROP TABLE visitantes;
SET FOREIGN_KEY_CHECKS=1;